import type { Column, Job } from '@/types/kanban';

export const NAVIGATION_ITEMS = [
  {
    name: 'Home',
    href: '/',
  },

  {
    name: 'Login',
    href: '/login',
  },
];

export const DEFAULT_COLUMNS: Column[] = [
  { id: 'attended', name: 'Attended Jobs', color: 'kanban-attended' },
  { id: 'rejected', name: 'Rejected Jobs', color: 'kanban-rejected' },
  { id: 'interview', name: 'Accepted to Interview', color: 'kanban-interview' },
];

export const DEFAULT_JOBS: Job[] = [
  // Attended Jobs
  {
    id: 'job-1',
    status: 'attended',
    jobTitle: 'Frontend Developer',
    companyName: 'TechCorp',
    description: 'Frontend pozíció React és TypeScript ismerettel',
    salary: '$60k - $80k',
    skills: ['React', 'TypeScript', 'Tailwind'],
    order: 1,
  },
  {
    id: 'job-2',
    status: 'attended',
    jobTitle: 'UI/UX Designer',
    companyName: 'DesignHub',
    description: 'Design pozíció Figma és Sketch ismerettel',
    salary: '$50k - $70k',
    skills: ['Figma', 'Sketch', 'Adobe XD'],
    order: 2,
  },
  {
    id: 'job-3',
    status: 'attended',
    jobTitle: 'Fullstack Developer',
    companyName: 'WebSolutions',
    description: 'Node + React fejlesztő',
    salary: '$65k - $85k',
    skills: ['Node.js', 'React', 'PostgreSQL'],
    order: 3,
  },
  {
    id: 'job-4',
    status: 'attended',
    jobTitle: 'QA Engineer',
    companyName: 'QualityFirst',
    description: 'Automatizált tesztelés',
    salary: '$55k - $70k',
    skills: ['Selenium', 'Cypress', 'Jest'],
    order: 4,
  },
  {
    id: 'job-5',
    status: 'attended',
    jobTitle: 'DevOps Engineer',
    companyName: 'CloudOps',
    description: 'CI/CD és AWS infrastruktúra',
    salary: '$70k - $90k',
    skills: ['AWS', 'Docker', 'Kubernetes'],
    order: 5,
  },
  {
    id: 'job-6',
    status: 'attended',
    jobTitle: 'Mobile Developer',
    companyName: 'AppWorld',
    description: 'iOS és Android fejlesztés',
    salary: '$60k - $80k',
    skills: ['React Native', 'Swift', 'Kotlin'],
    order: 6,
  },
  {
    id: 'job-7',
    status: 'attended',
    jobTitle: 'Technical Writer',
    companyName: 'DocuTech',
    description: 'Technical dokumentáció készítése',
    salary: '$45k - $60k',
    skills: ['Markdown', 'Docs', 'Confluence'],
    order: 7,
  },

  // Rejected Jobs
  {
    id: 'job-8',
    status: 'rejected',
    jobTitle: 'Backend Engineer',
    companyName: 'DataFlow',
    description: 'Java backend pozíció',
    salary: '$65k - $85k',
    skills: ['Java', 'Spring', 'MySQL'],
    order: 8,
  },
  {
    id: 'job-9',
    status: 'rejected',
    jobTitle: 'Frontend Developer',
    companyName: 'PixelPerfect',
    description: 'React + Tailwind fejlesztő',
    salary: '$60k - $80k',
    skills: ['React', 'Tailwind', 'TypeScript'],
    order: 9,
  },
  {
    id: 'job-10',
    status: 'rejected',
    jobTitle: 'Product Manager',
    companyName: 'ProdManage',
    description: 'Projekt és termék menedzsment',
    salary: '$70k - $90k',
    skills: ['Jira', 'Agile', 'Scrum'],
    order: 10,
  },
  {
    id: 'job-11',
    status: 'rejected',
    jobTitle: 'Data Analyst',
    companyName: 'DataMetrics',
    description: 'Adatvizualizáció és elemzés',
    salary: '$55k - $70k',
    skills: ['Python', 'SQL', 'Tableau'],
    order: 11,
  },
  {
    id: 'job-12',
    status: 'rejected',
    jobTitle: 'Support Engineer',
    companyName: 'HelpDeskPro',
    description: 'Technikai ügyfélszolgálat',
    salary: '$45k - $60k',
    skills: ['Zendesk', 'CRM', 'Customer Support'],
    order: 12,
  },
  {
    id: 'job-13',
    status: 'rejected',
    jobTitle: 'Marketing Specialist',
    companyName: 'AdWorld',
    description: 'Digitális marketing',
    salary: '$50k - $65k',
    skills: ['SEO', 'Google Ads', 'Analytics'],
    order: 13,
  },
  {
    id: 'job-14',
    status: 'rejected',
    jobTitle: 'HR Manager',
    companyName: 'PeopleFirst',
    description: 'Toborzás és HR menedzsment',
    salary: '$60k - $75k',
    skills: ['HR', 'Recruitment', 'Onboarding'],
    order: 14,
  },

  // Accepted to Interview
  {
    id: 'job-15',
    status: 'interview',
    jobTitle: 'Backend Engineer',
    companyName: 'DataSolutions',
    description: 'Node.js backend fejlesztő pozíció',
    salary: '$70k - $90k',
    skills: ['Node.js', 'Express', 'MongoDB'],
    interviewDate: '2026-02-15',
    order: 15,
  },
  {
    id: 'job-16',
    status: 'interview',
    jobTitle: 'Frontend Developer',
    companyName: 'UIStars',
    description: 'React + TypeScript fejlesztő',
    salary: '$60k - $80k',
    skills: ['React', 'TypeScript', 'Tailwind'],
    interviewDate: '2026-02-18',
    order: 16,
  },
  {
    id: 'job-17',
    status: 'interview',
    jobTitle: 'DevOps Engineer',
    companyName: 'CloudOps',
    description: 'AWS + CI/CD infrastruktúra',
    salary: '$70k - $95k',
    skills: ['AWS', 'Docker', 'Kubernetes'],
    interviewDate: '2026-02-20',
    order: 17,
  },
  {
    id: 'job-18',
    status: 'interview',
    jobTitle: 'Mobile Developer',
    companyName: 'AppWorld',
    description: 'React Native / iOS / Android',
    salary: '$60k - $85k',
    skills: ['React Native', 'Swift', 'Kotlin'],
    interviewDate: '2026-02-22',
    order: 18,
  },
  {
    id: 'job-19',
    status: 'interview',
    jobTitle: 'Data Analyst',
    companyName: 'DataMetrics',
    description: 'Adatvizualizáció és elemzés',
    salary: '$55k - $75k',
    skills: ['Python', 'SQL', 'Tableau'],
    interviewDate: '2026-02-25',
    order: 19,
  },
  {
    id: 'job-20',
    status: 'interview',
    jobTitle: 'QA Engineer',
    companyName: 'QualityFirst',
    description: 'Automatizált tesztelés',
    salary: '$55k - $70k',
    skills: ['Selenium', 'Cypress', 'Jest'],
    interviewDate: '2026-02-28',
    order: 20,
  },
  {
    id: 'job-21',
    status: 'interview',
    jobTitle: 'Product Manager',
    companyName: 'ProdManage',
    description: 'Projekt- és termékmenedzsment',
    salary: '$70k - $90k',
    skills: ['Jira', 'Agile', 'Scrum'],
    interviewDate: '2026-03-02',
    order: 21,
  },
];
